import type { Metadata } from "next";
import { EB_Garamond, Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const ebGaramond = EB_Garamond({
  weight: ["400", "500", "600"],
  variable: "--font-eb-garamond",
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

const beVietnamPro = Be_Vietnam_Pro({
  weight: ["400", "500", "600", "700"],
  variable: "--font-be-vietnam-pro",
  subsets: ["latin", "latin-ext"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ebGaramond.variable} ${beVietnamPro.variable} h-full antialiased`}
    >
      <body className=" ">
        <div className="min-h-screen flex flex-col bg-[#f8efea]">
          <Navbar />
          <main className="grow items-center"> {children}</main>
        </div>
      </body>
    </html>
  );
}
